name: lambda-api
on:
  push:
    branches: [main]
    paths:
      # Build when there are changes in the directory that holds the component,
      # or when this workflow file is changed
      - "lambda-api/**"
      - ".github/workflows/lambda-api.yml"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: git setup
        run: |
          git config --global user.name "${{ github.workflow }}"
          git config --global user.email "gha@scloud/${{ github.workflow }}"

      - name: Build
        working-directory: ./${{ github.workflow }}
        run: |
          yarn
          yarn lint
          yarn test
          yarn package

      - name: Publish
        working-directory: ./${{ github.workflow }}
        run: |
          # npm version patch
          npm publish --provenance --access public

      - name: Push
        working-directory: ./${{ github.workflow }}
        if: always()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Push updated pakage.json to Github
          # We need this to happen always to avoid the repo getting stuck on an already-published version
          git commit -am "Patch version" || true
          git pull --rebase
          git push
