name: lambda-api
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: git setup
        run: |
          git config --global user.name "${{ vars.GITHUB_WORKFLOW }}"
          git config --global user.email "gha@scloud"

      - name: Build
        working-directory: ./${{ vars.GITHUB_WORKFLOW }}
        run: |
          yarn
          yarn lint
          yarn test
          yarn compile

      - name: Publish
        working-directory: ./${{ vars.GITHUB_WORKFLOW }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn version patch
          yarn publish --access public
          git push
