name: static

on:
  push:
    branches:
      - main
    paths:
    # Build when there are changes in the directory,
    # or when this workflow file is changed
    - 'static/**'
    - '.github/workflows/static.yml'

jobs:
  static_content:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Commit hash
      working-directory: static
      run: |
        echo $(git rev-parse --short HEAD) > public/COMMIT_HASH

    - name: Sass
      working-directory: static
      run: |
        npm ci
        npm run sass

    - name: Javascript
      working-directory: static
      run: |
        mkdir -p public/javascripts/vendor

        curl https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js --output public/javascripts/vendor/modernizr.js

        cp node_modules/govuk-frontend/govuk/all.js public/javascripts

    - name: Upload to s3
      env:
        BUCKET: ${{ secrets.WEB_STATICBUCKET }}
      working-directory: static
      run: |
        aws s3 sync --delete ./public/ s3://${BUCKET}/public/

    - name: Invalidate Cloudfront
      env:
        DISTRIBUTION_ID: ${{ secrets.WEB_DISTRIBUTIONID }}
      working-directory: static
      run: |
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Static content
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON_EMOJI: ":github_octocat:"
        SLACK_CHANNEL: build
