name: static

on:
  push:
    branches:
      - main
    paths:
    # Build when there are changes in the directory,
    # or when this workflow file is changed
    - 'static/**'
    - '.github/workflows/static.yml'
  workflow_dispatch:

jobs:
  static_content:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Commit hash
      working-directory: static
      run: |
        echo $(git rev-parse HEAD) > public/COMMIT_HASH

    - name: Upload to s3
      env:
        STATIC_BUCKET: ${{ secrets.STATIC_BUCKET }}
      working-directory: static
      run: |
        aws s3 sync ./public/ s3://${STATIC_BUCKET}/

    - name: Invalidate Cloudfront
      env:
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
      working-directory: static
      run: |
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Static build
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON_EMOJI: ":github_octocat:"
        SLACK_FOOTER: Github Actions
        SLACK_CHANNEL: general
